#!/usr/bin/env bash
# Auto-generated by scripts/install.sh
export PANEL_SECRET_KEY="ae9240ebf8ad30214fd817243c6b50c200b2391c3aa9ef42b6c2e432f6fec50f"
export PANEL_REDIS_URL="redis://127.0.0.1:6379/0"
export DATABASE_URL="postgresql+psycopg2://paneluser:panelpass@127.0.0.1:5432/paneldb"
