const express = require('express');
const router = express.Router();
const bcrypt = require('bcryptjs');
const fs = require('fs');
const path = require('path');
const { testConnection, initPool, initializeTables, setSetting } = require('../database/schema');
const { seedEggs } = require('../daemon/eggManager');

router.get('/', async (req, res) => {
  res.render('install', {
    error: null,
    success: null,
    step: req.query.step || 1,
    dbHost: process.env.DB_HOST || '127.0.0.1',
    dbPort: process.env.DB_PORT || 5432,
    dbName: process.env.DB_NAME || 'panel_db',
    dbUser: process.env.DB_USER || 'panel'
  });
});

router.post('/setup', async (req, res) => {
  const {
    db_host, db_port, db_name, db_user, db_pass,
    web_hostname, web_caddy_email,
    site_title, site_motd, social_discord, social_twitter, social_github,
    admin_user, admin_email, admin_pass
  } = req.body;

  try {
    const dbConfig = {
      host: db_host || '127.0.0.1',
      port: parseInt(db_port || 5432),
      database: db_name || 'panel_db',
      user: db_user || 'panel',
      password: db_pass || 'panel_secure_password'
    };

    const connected = await testConnection(dbConfig);
    if (!connected) {
      return res.render('install', { error: 'Database Connection Failed. Please verify credentials.', success: null, step: 2 });
    }

    initPool(dbConfig);
    await initializeTables();

    await setSetting('SITE_TITLE', site_title || '-OZ- Panel Hub Enterprise');
    await setSetting('SITE_MOTD', site_motd || 'Next-Gen Premium Game Server Orchestrator');
    await setSetting('SOCIAL_DISCORD', social_discord || 'https://discord.gg/ozpanel');
    await setSetting('SOCIAL_TWITTER', social_twitter || 'https://twitter.com/ozpanel');
    await setSetting('SOCIAL_GITHUB', social_github || 'https://github.com/ozpanel');
    await setSetting('WEB_HOSTNAME', web_hostname || '127.0.0.1');

    await seedEggs();

    const hashed = await bcrypt.hash(admin_pass, 10);
    const { query } = require('../database/schema');
    await query(`
      INSERT INTO users (username, email, password_hash, role, bio) 
      VALUES ($1, $2, $3, 'admin', 'Master Administrator account for -OZ- Panel Hub Enterprise.')
      ON CONFLICT (username) DO UPDATE SET password_hash = EXCLUDED.password_hash, role = 'admin'
    `, [admin_user, admin_email, hashed]);

    const caddyfileTemplate = `
# Automatically generated by -OZ- Panel Hub Installation Sentinel
${web_hostname || 'localhost'}:80 {
    reverse_proxy 127.0.0.1:3000
    encode gzip zstd
    file_server
}
`;
    fs.writeFileSync(path.join(__dirname, '../../Caddyfile.production'), caddyfileTemplate.trim(), 'utf8');

    await setSetting('INSTALLED', 'true');

    console.log('[Installer] -OZ- Master Installation executed successfully!');
    res.render('install_complete', { adminUser: admin_user, webHostname: web_hostname });

  } catch (err) {
    console.error('[Installer] Setup Error:', err);
    res.render('install', { error: `Installation Exception: ${err.message}`, success: null, step: 1 });
  }
});

module.exports = router;
