"""Add host, port, and rcon_password fields to Server model

Revision ID: 3fd9eaf414fb
Revises: bbda3883b503
Create Date: 2025-11-20 07:37:48.037536

"""

import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3fd9eaf414fb"
down_revision = "bbda3883b503"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with sa.op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('port', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rcon_password', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with sa.op.batch_alter_table('server', schema=None) as batch_op:
        batch_op.drop_column('rcon_password')
        batch_op.drop_column('port')
        batch_op.drop_column('host')
    # ### end Alembic commands ###