"""autogen cms/forum (include cms/forum)

Revision ID: bbda3883b503
Revises: 2ca607eff9c8
Create Date: 2025-11-18 06:50:05.681462

"""

# revision identifiers, used by Alembic.
revision = "bbda3883b503"
down_revision = "2ca607eff9c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
