"""Add 2FA and security fields to User model

Revision ID: dc4e5affd5bc
Revises: 3fd9eaf414fb
Create Date: 2025-11-20 07:45:12.345678

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "dc4e5affd5bc"
down_revision = "3fd9eaf414fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("totp_secret", sa.String(length=32), nullable=True)
        )
        batch_op.add_column(
            sa.Column("totp_enabled", sa.Boolean(), nullable=True, default=False)
        )
        batch_op.add_column(sa.Column("backup_codes", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("last_login", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column("login_attempts", sa.Integer(), nullable=True, default=0)
        )
        batch_op.add_column(sa.Column("locked_until", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with sa.op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("locked_until")
        batch_op.drop_column("login_attempts")
        batch_op.drop_column("last_login")
        batch_op.drop_column("backup_codes")
        batch_op.drop_column("totp_enabled")
        batch_op.drop_column("totp_secret")
    # ### end Alembic commands ###
