#!/usr/bin/env bash
set -euo pipefail

# Interactive installer for the Panel app
# - Creates a Python virtualenv and installs requirements
# - Writes an env file with configuration
# - Initializes the database and optionally creates an admin user
# - Sets up local instance directories

HERE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$HERE_DIR/.." && pwd)"
cd "$ROOT_DIR"

if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 not found. Please install Python 3." >&2
  exit 1
fi

prompt() {
  local msg="$1"; shift
  local def="${1-}"; shift || true
  local var
  if [[ -n "$def" ]]; then
    read -rp "$msg [$def]: " var || true
    echo "${var:-$def}"
  else
    read -rp "$msg: " var || true
    echo "$var"
  fi
}

prompt_secret() {
  local msg="$1"
  local var
  read -rsp "$msg: " var || true
  echo
  echo "$var"
}

confirm() {
  local msg="$1"; shift
  local def="${1:-N}"; shift || true
  local ans
  read -rp "$msg [$def]: " ans || true
  ans="${ans:-$def}"
  case "$ans" in
    y|Y|yes|YES) return 0;;
    *) return 1;;
  esac
}

# 1) Environment selection
ENVIRONMENT="$(prompt "Environment (dev/prod)" "dev")"
if [[ "$ENVIRONMENT" != "dev" && "$ENVIRONMENT" != "prod" ]]; then
  echo "Invalid environment: $ENVIRONMENT (expected 'dev' or 'prod')" >&2
  exit 1
fi

VENVDIR="$(prompt "Virtualenv directory" ".venv")"
REDIS_URL_DEFAULT="redis://127.0.0.1:6379/0"
REDIS_URL="$(prompt "Redis URL" "$REDIS_URL_DEFAULT")"

# Optional system packages
if confirm "Install system packages via apt (espeak, gdb, unzip, redis-server)?" N; then
  if command -v apt >/dev/null 2>&1; then
    sudo apt update
    sudo apt install -y espeak gdb unzip redis-server
  else
    echo "apt not found; skipping system package installation." >&2
  fi
fi

# Generate a secret key
SECRET_KEY="$(python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
)"

USE_SQLITE=1
SQLITE_URI="sqlite:///panel_dev.db"
DB_USER="paneluser"
DB_PASS="panelpass"
DB_HOST="127.0.0.1"
DB_NAME="paneldb"

if [[ "$ENVIRONMENT" == "prod" ]]; then
  USE_SQLITE=0
  DB_USER="$(prompt "MySQL user" "$DB_USER")"
  DB_PASS="$(prompt_secret "MySQL password")"
  DB_HOST="$(prompt "MySQL host" "$DB_HOST")"
  DB_NAME="$(prompt "MySQL database name" "$DB_NAME")"
else
  # dev: allow overriding SQLite URI
  SQLITE_URI="$(prompt "SQLite URI" "$SQLITE_URI")"
fi

CREATE_ADMIN=0
if confirm "Create an initial system admin user now?" N; then
  CREATE_ADMIN=1
  ADMIN_EMAIL="$(prompt "Admin email" "admin@example.com")"
  ADMIN_FIRST="$(prompt "Admin first name" "Admin")"
  ADMIN_LAST="$(prompt "Admin last name" "User")"
  ADMIN_DOB="$(prompt "Admin date of birth (YYYY-MM-DD)" "2000-01-01")"
  while true; do
    ADMIN_PASS1="$(prompt_secret "Admin password")"
    ADMIN_PASS2="$(prompt_secret "Confirm admin password")"
    if [[ "$ADMIN_PASS1" == "$ADMIN_PASS2" && -n "$ADMIN_PASS1" ]]; then
      break
    fi
    echo "Passwords do not match or empty. Please try again." >&2
  done
fi

# 2) Create virtualenv and install requirements
python3 -m venv "$VENVDIR"
# shellcheck disable=SC1090
source "$VENVDIR/bin/activate"
pip install -U pip wheel
pip install -r requirements.txt

# 3) Create instance directories
mkdir -p instance/theme_assets

# 4) Write environment file
ENV_FILE="scripts/env.sh"
{
  echo "#!/usr/bin/env bash"
  echo "# Auto-generated by scripts/install.sh"
  echo "export PANEL_SECRET_KEY=\"$SECRET_KEY\""
  echo "export PANEL_REDIS_URL=\"$REDIS_URL\""
  if [[ "$USE_SQLITE" -eq 1 ]]; then
    echo "export PANEL_USE_SQLITE=1"
    echo "export PANEL_SQLITE_URI=\"$SQLITE_URI\""
  else
    echo "export PANEL_DB_USER=\"$DB_USER\""
    echo "export PANEL_DB_PASS=\"$DB_PASS\""
    echo "export PANEL_DB_HOST=\"$DB_HOST\""
    echo "export PANEL_DB_NAME=\"$DB_NAME\""
  fi
} > "$ENV_FILE"
chmod +x "$ENV_FILE" || true

echo "Wrote $ENV_FILE"

# 5) Initialize database and optionally create admin
# shellcheck disable=SC1090
source "$ENV_FILE"
python3 - <<PY
from datetime import date
from app import app, db, User

with app.app_context():
    db.create_all()
    print("Database tables created.")
PY

if [[ "$CREATE_ADMIN" -eq 1 ]]; then
python3 - <<PY
from datetime import date
from app import app, db, User

email = "$ADMIN_EMAIL".lower().strip()
first = "$ADMIN_FIRST".strip()
last = "$ADMIN_LAST".strip()
dob_str = "$ADMIN_DOB".strip()
password = "$ADMIN_PASS1"

# parse DOB
try:
    y,m,d = [int(x) for x in dob_str.split('-')]
    dob = date(y,m,d)
except Exception:
    dob = date(2000,1,1)

with app.app_context():
    u = User.query.filter_by(email=email).first()
    if u is None:
        u = User(first_name=first, last_name=last, email=email, dob=dob, role='system_admin')
        u.set_password(password)
        db.session.add(u)
        db.session.commit()
        print(f"Created system admin user: {email}")
    else:
        print(f"User already exists: {email} (role={u.role})")
PY
fi

cat <<'OUT'

Installation complete.

Next steps (development):
  1) Activate the venv and env:
     source "${VENVDIR}/bin/activate"
     source scripts/env.sh
  2) Run the app:
     python app.py

For production:
  - Copy and adjust the systemd service files in deploy/ (WorkingDirectory, PATH)
  - Point gunicorn at app:app, ensure env variables are set for the service
  - Configure nginx with deploy/nginx_game_chrisvanek.conf

OUT
