#!/usr/bin/env bash
set -euo pipefail

# Interactive installer for the Panel app
# - Creates a Python virtualenv and installs requirements
# - Writes an env file with configuration
# - Initializes the database and optionally creates an admin user
# - Sets up local instance directories

HERE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$HERE_DIR/.." && pwd)"
cd "$ROOT_DIR"

prompt() {
  local msg="$1"; shift
  local def="${1-}"; shift || true
  local var
  if [[ -n "$def" ]]; then
    read -rp "$msg [$def]: " var || true
    echo "${var:-$def}"
  else
    read -rp "$msg: " var || true
    echo "$var"
  fi
}

prompt_secret() {
  local msg="$1"
  local var
  read -rsp "$msg: " var || true
  echo
  echo "$var"
}

confirm() {
  local msg="$1"; shift
  local def="${1:-N}"; shift || true
  local ans
  read -rp "$msg [$def]: " ans || true
  ans="${ans:-$def}"
  case "$ans" in
    y|Y|yes|YES) return 0;;
    *) return 1;;
  esac
}

# ----- Apt helpers -----
has_cmd() { command -v "$1" >/dev/null 2>&1; }
apt_available() { has_cmd apt; }
SUDO=""; if [[ ${EUID:-$(id -u)} -ne 0 ]] && has_cmd sudo; then SUDO="sudo"; fi
APT_UPDATED=0
apt_update_once() { if [[ $APT_UPDATED -eq 0 ]]; then $SUDO apt update; APT_UPDATED=1; fi }
ensure_apt_pkgs() {
  # usage: ensure_apt_pkgs pkg1 pkg2 ...
  local missing=()
  for p in "$@"; do
    if ! dpkg -s "$p" >/dev/null 2>&1; then
      missing+=("$p")
    fi
  done
  if ((${#missing[@]})); then
    echo "Installing packages: ${missing[*]}"
    apt_update_once
    $SUDO apt install -y "${missing[@]}"
  else
    echo "All requested packages already installed."
  fi
}

# Pre-flight: ensure core tools via apt if missing
if ! has_cmd python3; then
  if apt_available; then
    echo "python3 not found. Attempting to install via apt..."
    ensure_apt_pkgs python3
  else
    echo "python3 not found and apt not available. Please install Python 3." >&2
    exit 1
  fi
fi

# 1) Environment selection
ENVIRONMENT="$(prompt "Environment (dev/prod)" "dev")"
if [[ "$ENVIRONMENT" != "dev" && "$ENVIRONMENT" != "prod" ]]; then
  echo "Invalid environment: $ENVIRONMENT (expected 'dev' or 'prod')" >&2
  exit 1
fi

VENVDIR="$(prompt "Virtualenv directory" ".venv")"
REDIS_URL_DEFAULT="redis://127.0.0.1:6379/0"
REDIS_URL="$(prompt "Redis URL" "$REDIS_URL_DEFAULT")"

# System dependency checks and installation
if apt_available && confirm "Check and install missing system dependencies via apt?" Y; then
  # Essential for runtime and script features
  REQ_PKGS=(python3 python3-venv unzip espeak)
  # Helpful utilities used in repo/scripts and optional services
  OPT_PKGS=(gdb redis-server make)
  ensure_apt_pkgs "${REQ_PKGS[@]}" "${OPT_PKGS[@]}"
else
  echo "Skipping automatic system dependency installation."
fi

# Generate a secret key
SECRET_KEY="$(python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
)"

USE_SQLITE=1
SQLITE_URI="sqlite:///panel_dev.db"
DB_USER="paneluser"
DB_PASS="panelpass"
DB_HOST="127.0.0.1"
DB_NAME="paneldb"

if [[ "$ENVIRONMENT" == "prod" ]]; then
  USE_SQLITE=0
  DB_USER="$(prompt "MySQL user" "$DB_USER")"
  DB_PASS="$(prompt_secret "MySQL password")"
  DB_HOST="$(prompt "MySQL host" "$DB_HOST")"
  DB_NAME="$(prompt "MySQL database name" "$DB_NAME")"
else
  # dev: allow overriding SQLite URI
  SQLITE_URI="$(prompt "SQLite URI" "$SQLITE_URI")"
fi

CREATE_ADMIN=0
if confirm "Create an initial system admin user now?" N; then
  CREATE_ADMIN=1
  ADMIN_EMAIL="$(prompt "Admin email" "admin@example.com")"
  ADMIN_FIRST="$(prompt "Admin first name" "Admin")"
  ADMIN_LAST="$(prompt "Admin last name" "User")"
  ADMIN_DOB="$(prompt "Admin date of birth (YYYY-MM-DD)" "2000-01-01")"
  while true; do
    ADMIN_PASS1="$(prompt_secret "Admin password")"
    ADMIN_PASS2="$(prompt_secret "Confirm admin password")"
    if [[ "$ADMIN_PASS1" == "$ADMIN_PASS2" && -n "$ADMIN_PASS1" ]]; then
      break
    fi
    echo "Passwords do not match or empty. Please try again." >&2
  done
fi

# 2) Create virtualenv and install requirements
python3 -m venv "$VENVDIR"
# shellcheck disable=SC1090
source "$VENVDIR/bin/activate"
pip install -U pip wheel
pip install -r requirements.txt

# 2.5) Optionally install Playwright browsers for E2E tests
INSTALL_PLAYWRIGHT=0
if confirm "Install Playwright Chromium for E2E tests?" N; then
  INSTALL_PLAYWRIGHT=1
  echo "Installing Playwright Chromium..."
  python -m playwright install chromium || {
    echo "Warning: Playwright install failed. E2E tests may not run." >&2
  }
fi

# 3) Create instance directories
mkdir -p instance/theme_assets

# 4) Write environment file
ENV_FILE="scripts/env.sh"
{
  echo "#!/usr/bin/env bash"
  echo "# Auto-generated by scripts/install.sh"
  echo "export PANEL_SECRET_KEY=\"$SECRET_KEY\""
  echo "export PANEL_REDIS_URL=\"$REDIS_URL\""
  if [[ "$USE_SQLITE" -eq 1 ]]; then
    echo "export PANEL_USE_SQLITE=1"
    echo "export PANEL_SQLITE_URI=\"$SQLITE_URI\""
  else
    echo "export PANEL_DB_USER=\"$DB_USER\""
    echo "export PANEL_DB_PASS=\"$DB_PASS\""
    echo "export PANEL_DB_HOST=\"$DB_HOST\""
    echo "export PANEL_DB_NAME=\"$DB_NAME\""
  fi
} > "$ENV_FILE"
chmod +x "$ENV_FILE" || true

echo "Wrote $ENV_FILE"

# 5) Initialize database and optionally create admin
# shellcheck disable=SC1090
source "$ENV_FILE"
python3 - <<PY
from datetime import date
from app import app, db, User

with app.app_context():
    db.create_all()
    print("Database tables created.")
PY

if [[ "$CREATE_ADMIN" -eq 1 ]]; then
python3 - <<PY
from datetime import date
from app import app, db, User

email = "$ADMIN_EMAIL".lower().strip()
first = "$ADMIN_FIRST".strip()
last = "$ADMIN_LAST".strip()
dob_str = "$ADMIN_DOB".strip()
password = "$ADMIN_PASS1"

# parse DOB
try:
    y,m,d = [int(x) for x in dob_str.split('-')]
    dob = date(y,m,d)
except Exception:
    dob = date(2000,1,1)

with app.app_context():
    u = User.query.filter_by(email=email).first()
    if u is None:
        u = User(first_name=first, last_name=last, email=email, dob=dob, role='system_admin')
        u.set_password(password)
        db.session.add(u)
        db.session.commit()
        print(f"Created system admin user: {email}")
    else:
        print(f"User already exists: {email} (role={u.role})")
PY
fi

cat <<'OUT'

Installation complete.

Next steps (development):
  1) Activate the venv and env:
     source "${VENVDIR}/bin/activate"
     source scripts/env.sh
  2) Run the app:
     python app.py
OUT

if [[ "$INSTALL_PLAYWRIGHT" -eq 1 ]]; then
cat <<'OUT'
  3) Run tests (including E2E):
     pytest -q

OUT
else
cat <<'OUT'
  3) Run tests (note: E2E tests will be skipped without Playwright):
     pytest -q
     
     To enable E2E tests later:
       source .venv/bin/activate
       python -m playwright install chromium

OUT
fi

cat <<'OUT'
For production:
  - Copy and adjust the systemd service files in deploy/ (WorkingDirectory, PATH)
  - Point gunicorn at app:app, ensure env variables are set for the service
  - Configure nginx with deploy/nginx_game_chrisvanek.conf

OUT
